### ISSUE TITLE
Question regarding usage

### ISSUE THREAD

**Issue by sersoage** [benbo/interactive-weak-supervision#1]
Hi, first of all thanks for the great paper and the implementation. I tried running the ipynb on IMDB dataset, when I run the user interactive (not oracle), I get the first 4 random questions but then it does not move forward, any idea what might be happening. Thanks again!

**Comment by benbo** [comment]
Hey. Thanks for checking out our project. Could you tell me 
a) how exactly does it stop? E.g. Is the bar full at 4/4 or does a new status bar get initiated? 
b) could you check on the console where you jupyter if any error messages appear? 

I have a feeling this may be an issue with the multi-processing of the MLP ensemble, but I cannot be sure. 

Also, for now you could  try the following things:
1) set `numthreads = 1`
2) restart the kernel and make sure that you do not run the oracle first. So set `auto=False` and start with the user experiment.

**Comment by sersoage** [comment]
Yes that seems to be the issue, no error messages just stopped, It got stuck on 0/50 before but after setting numthreads = 1 it works. Thanks again!

**Comment by benbo** [comment]
Sure thing @sersoage. And if you do figure out why multiprocessing was causing issues do let us know. I haven't run into that problem on our machines.
